language: perl
os:
  - linux
  - osx
node_js:
  - "8"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
cache:
  bundler: true
  directories:
  - ~/.npm
  - node_modules # NPM packages
before_install:
    - nvm install 8
    - perl --version
    - node --version
    # - export PERL5OPT="-I${HOME}/perl5/lib/perl5"
    - echo $PERL5OPT
    - echo $TRAVIS_OS_NAME
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpanm PadWalker; fi
install:
    - travis_retry npm install
stages:
  - test
  - name: release
    if: branch = master

script:
    - npm run tslint
    - travis_retry npm test # This happens on linux, should investigate
jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      script:
        - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
